# Defines the paths and properties for the Banking77 dataset.
name: "banking77"

# Paths are relative to the project root directory (llm-trust-lens/)
path: "data/banking/train.tsv"
label_map_path: "data/banking77/idx2label.csv"

# The names of the columns in train.csv
text_column: "text"
label_column: "label"
