# Defines the paths and properties for the Banking77 dataset.
name: "banking"    # options: 'banking', 'stackoverflow', 'oos'

# Paths are relative to the project root directory (llm-trust-lens/)
path: "data/banking_simulate_csv"
label_map_path: "data/banking_simulate_csv/banking77_idx2label.csv"

# The names of the columns in train.csv
text_column: "text"
label_column: "label"


